package com.mobile.iexpense.core.component.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class CustomThemeColors(
    val backgroundPrimary: Color,
    val backgroundSecondary: Color,
    val backgroundTertiary: Color,
    val backgroundCardPrimary: Color,
    val backgroundCardSecondary: Color,
    val backgroundCardTertiary: Color,
    val backgroundSurfaceDim: Color,
    val backgroundSurfaceBright: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val textPlaceholder: Color,
    val textColorOnTheme: Color,
    val textInverse: Color,
    val textCritical: Color,
    val textOnTertiary: Color,
    val borderPrimary: Color,
    val borderSecondary: Color,
    val borderTertiary: Color,
    val borderCritical: Color,
    val iconPrimary: Color,
    val iconSecondary: Color,
    val iconTertiary: Color,
    val iconCritical: Color,
    val iconOnTheme: Color,
    val iconOnTertiary: Color,
    val themeColor: Color,
    val themeInverse: Color,
    val themeDim: Color,
    val themeSurfaceTint: Color,
    val fixedPrimary: Color,
    val fixedPrimaryDim: Color,
    val fixedOnPrimary: Color,
    val fixedSecondary: Color,
    val fixedSecondaryDim: Color,
    val fixedOnSecondary: Color,
    val fixedTertiary: Color,
    val fixedTertiaryDim: Color,
    val fixedOnTertiary: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color
)

fun customThemeColorsOf(
    backgroundPrimary: Color,
    backgroundSecondary: Color,
    backgroundTertiary: Color,
    backgroundCardPrimary: Color,
    backgroundCardSecondary: Color,
    backgroundCardTertiary: Color,
    backgroundSurfaceDim: Color,
    backgroundSurfaceBright: Color,
    textPrimary: Color,
    textSecondary: Color,
    textTertiary: Color,
    textPlaceholder: Color,
    textColorOnTheme: Color,
    textInverse: Color,
    textCritical: Color,
    textOnTertiary: Color,
    borderPrimary: Color,
    borderSecondary: Color,
    borderTertiary: Color,
    borderCritical: Color,
    iconPrimary: Color,
    iconSecondary: Color,
    iconTertiary: Color,
    iconCritical: Color,
    iconOnTheme: Color,
    iconOnTertiary: Color,
    themeColor: Color,
    themeInverse: Color,
    themeDim: Color,
    themeSurfaceTint: Color,
    fixedPrimary: Color,
    fixedPrimaryDim: Color,
    fixedOnPrimary: Color,
    fixedSecondary: Color,
    fixedSecondaryDim: Color,
    fixedOnSecondary: Color,
    fixedTertiary: Color,
    fixedTertiaryDim: Color,
    fixedOnTertiary: Color,
    inverseSurface: Color,
    inverseOnSurface: Color,
    error: Color,
    onError: Color,
    errorContainer: Color,
    onErrorContainer: Color
): CustomThemeColors = CustomThemeColors(
    backgroundPrimary = backgroundPrimary,
    backgroundSecondary = backgroundSecondary,
    backgroundTertiary = backgroundTertiary,
    backgroundCardPrimary = backgroundCardPrimary,
    backgroundCardSecondary = backgroundCardSecondary,
    backgroundCardTertiary = backgroundCardTertiary,
    backgroundSurfaceDim = backgroundSurfaceDim,
    backgroundSurfaceBright = backgroundSurfaceBright,
    textPrimary = textPrimary,
    textSecondary = textSecondary,
    textTertiary = textTertiary,
    textPlaceholder = textPlaceholder,
    textColorOnTheme = textColorOnTheme,
    textInverse = textInverse,
    textCritical = textCritical,
    textOnTertiary = textOnTertiary,
    borderPrimary = borderPrimary,
    borderSecondary = borderSecondary,
    borderTertiary = borderTertiary,
    borderCritical = borderCritical,
    iconPrimary = iconPrimary,
    iconSecondary = iconSecondary,
    iconTertiary = iconTertiary,
    iconCritical = iconCritical,
    iconOnTheme = iconOnTheme,
    iconOnTertiary = iconOnTertiary,
    themeColor = themeColor,
    themeInverse = themeInverse,
    themeDim = themeDim,
    themeSurfaceTint = themeSurfaceTint,
    fixedPrimary = fixedPrimary,
    fixedPrimaryDim = fixedPrimaryDim,
    fixedOnPrimary = fixedOnPrimary,
    fixedSecondary = fixedSecondary,
    fixedSecondaryDim = fixedSecondaryDim,
    fixedOnSecondary = fixedOnSecondary,
    fixedTertiary = fixedTertiary,
    fixedTertiaryDim = fixedTertiaryDim,
    fixedOnTertiary = fixedOnTertiary,
    inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer
)

val LocalCustomColors = staticCompositionLocalOf {
    customThemeColorsOf(
        backgroundPrimary = Color.Unspecified,
        backgroundSecondary = Color.Unspecified,
        backgroundTertiary = Color.Unspecified,
        backgroundCardPrimary = Color.Unspecified,
        backgroundCardSecondary = Color.Unspecified,
        backgroundCardTertiary = Color.Unspecified,
        backgroundSurfaceDim = Color.Unspecified,
        backgroundSurfaceBright = Color.Unspecified,
        textPrimary = Color.Unspecified,
        textSecondary = Color.Unspecified,
        textTertiary = Color.Unspecified,
        textPlaceholder = Color.Unspecified,
        textColorOnTheme = Color.Unspecified,
        textInverse = Color.Unspecified,
        textCritical = Color.Unspecified,
        textOnTertiary = Color.Unspecified,
        borderPrimary = Color.Unspecified,
        borderSecondary = Color.Unspecified,
        borderTertiary = Color.Unspecified,
        borderCritical = Color.Unspecified,
        iconPrimary = Color.Unspecified,
        iconSecondary = Color.Unspecified,
        iconTertiary = Color.Unspecified,
        iconCritical = Color.Unspecified,
        iconOnTheme = Color.Unspecified,
        iconOnTertiary = Color.Unspecified,
        themeColor = Color.Unspecified,
        themeInverse = Color.Unspecified,
        themeDim = Color.Unspecified,
        themeSurfaceTint = Color.Unspecified,
        fixedPrimary = Color.Unspecified,
        fixedPrimaryDim = Color.Unspecified,
        fixedOnPrimary = Color.Unspecified,
        fixedSecondary = Color.Unspecified,
        fixedSecondaryDim = Color.Unspecified,
        fixedOnSecondary = Color.Unspecified,
        fixedTertiary = Color.Unspecified,
        fixedTertiaryDim = Color.Unspecified,
        fixedOnTertiary = Color.Unspecified,
        inverseSurface = Color.Unspecified,
        inverseOnSurface = Color.Unspecified,
        error = Color.Unspecified,
        onError = Color.Unspecified,
        errorContainer = Color.Unspecified,
        onErrorContainer = Color.Unspecified
    )
}